In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re  # text cleaning using regex

from nltk.corpus import stopwords  # NLP tools (stopwords + stemming)
# corpus - It provides ready-made text datasets so you don’t have to collect data yourself.
from nltk.stem.porter import PorterStemmer

from sklearn.feature_extraction.text import TfidfVectorizer  # converts text → numbers
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
#data preprocessing
#Loading the dataset to a pandas dataframe

fake_news_dataset = pd.read_csv("fake[1].csv", on_bad_lines='skip', engine='python')
true_news_dataset = pd.read_csv("true[1].csv", on_bad_lines='skip', engine='python')

In [23]:
#COMBINES BOTH DATASETS INTO ONE,

news_dataset = pd.concat([fake_news_dataset, true_news_dataset], ignore_index = True)
news_dataset

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
5048,State funding changes in spotlight in Republic...,WASHINGTON (Reuters) - Republican leaders soug...,politicsNews,"September 21, 2017"
5049,Republican Senator Collins 'leaning against' n...,WASHINGTON (Reuters) - Republican Senator Susa...,politicsNews,"September 22, 2017"
5050,Ex-Republican presidential candidate Bob Dole ...,(Reuters) - Former Republican presidential can...,politicsNews,"September 22, 2017"
5051,What's a 'dotard' anyway? Kim's insult to Trump,(Reuters) - North Korean leader Kim Jong Un ha...,politicsNews,"September 22, 2017"
5052,"Trump, South Korea's Moon agree to boost defen...",WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"September 22, 2017"

In [24]:
nwes_dataset = news_dataset.sample(frac=1).reset_index(drop = True)
news_dataset.head()
#it renumber rows properly

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [25]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [26]:
fake_news_dataset['label']=0
true_news_dataset['label']=1

In [27]:
news_dataset.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [28]:
news_dataset['content'] = news_dataset.title + " " + news_dataset.text

In [30]:
news_dataset = pd.concat([fake_news_dataset, true_news_dataset], ignore_index = True)
news_dataset['content'] = news_dataset.title + " " + news_dataset.text
news_dataset = news_dataset[['content' , 'label']]
news_dataset.head()

                                             content  label
0   Donald Trump Sends Out Embarrassing New Year’...      0
1   Drunk Bragging Trump Staffer Started Russian ...      0
2   Sheriff David Clarke Becomes An Internet Joke...      0
3   Trump Is So Obsessed He Even Has Obama’s Name...      0
4   Pope Francis Just Called Out Donald Trump Dur...      0

In [31]:
port_stem = PorterStemmer()
stop_words = set(stopwords.words('english'))

def stemming(content):
    # Remove non-alphabet and lowercase
    content = re.sub('[^a-zA-Z]', ' ', content).lower().split()

    # Remove stopwords and stem
    content = [port_stem.stem(word) for word in content if word not in stop_words]

    return ' '.join(content)

In [32]:
from tqdm import tqdm #tqdm = "taqaddum" (Arabic word meaning "progress")
tqdm.pandas()

# Assuming stemming function is defined in a previous cell
news_dataset['content'] = news_dataset['content'].progress_apply(stemming)
#cleans entire dataset.

100%|██████████| 5053/5053 [00:32<00:00, 157.45it/s]